### ISSUE TITLE
添加 PTR 查询支持失败

### ISSUE THREAD

**Issue by fanyeren** [wenerme/wps#2]
我在代码里添加了 PTR 支持

                        case *dns.PTR:
                                rr.Hdr = hrd
                                rr.Ptr = v.Content
                        case *dns.NS:
                                rr.Hdr = hrd
                                rr.Ns = v.Content

紧接着打印 rr 的数据正常

;; opcode: QUERY, status: NOERROR, id: 52396
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;99.3.10.10.in-addr.arpa.       IN       PTR

;; ANSWER SECTION:
99.3.10.10.in-addr.arpa.        60      IN      PTR     a.xxxx.com

但是客户端查询却是失败的，

$ host -t PTR  10.10.3.99
;; connection timed out; no servers could be reached

我是 golang 小白，如果作者有空的话，望不吝赐教。

**Comment by wenerme** [comment]
是 coredns pdsql 插件的问题么

**Comment by fanyeren** [comment]
@wenerme 是这个插件，不过现在不确定，我 golang 不熟，只是怀疑是 coredns 版本更新了，插件比较老，没有适配的缘故

**Comment by fanyeren** [comment]
补充，A 记录和 TXT 记录功能都正常，可以正常使用

**Comment by wenerme** [comment]
那你看是否还有问题，因为之前没有用到 PTR，不确定 pdns 存储的 PTR 格式

**Comment by fanyeren** [comment]
@wenerme 问题就是我前面提到的问题，同样的一个数据库，powerdns 模式就没有问题，结果正常

$ host -t PTR  10.10.3.99
99.3.10.10.in-addr.arpa domain name pointer a.xxxx.com.

**Comment by wenerme** [comment]
PTR 在数据库里存储是什么样的格式？

**Comment by fanyeren** [comment]
id: 5
  domain_id: 2
       name: 99.3.10.10.in-addr.arpa
       type: PTR
    content: a.xxxx.com
        ttl: 60
       prio: 0
change_date: 1547460566
   disabled: 0
  ordername: NULL
       auth: 1
 chang_date: NULL

**Comment by wenerme** [comment]
好的，那我有时间也看一下，如果你解决了也可以说一下

**Comment by fanyeren** [comment]
@wenerme 多谢

**Comment by wenerme** [comment]
已支持
