### ISSUE TITLE
Cannot include in CoreDNS v1.8.3

### ISSUE THREAD

**Issue by polettix** [wenerme/wps#7]
Hi! I'm totally new to the Go language and so apologies if I'm asking a trivial question.

I tried to include the pdsql plugin in CoreDNS v1.8.3 but to little avail:

- [docs](https://coredns.io/2017/07/25/compile-time-enabling-or-disabling-plugins/) seem to require a `go get github.com/wenerme/wps` but it later complains that it's not available.
- I then tried `go get github.com/wenerme/wps/coredns/plugin/pdsql` after reading one of the Issues here, only to get this:

```
go: found github.com/wenerme/wps/coredns/plugin/pdsql in github.com/wenerme/wps v0.0.0-20191105094758-5c216d826ac7
# github.com/wenerme/wps/coredns/plugin/pdsql
/root/go/pkg/mod/github.com/wenerme/wps@v0.0.0-20191105094758-5c216d826ac7/coredns/plugin/pdsql/setup.go:67:12: cannot use c (type *"github.com/caddyserver/caddy".Controller) as type *"github.com/coredns/caddy".Controller in argument to dnsserver.GetConfig
```

So I would ask:
- Is there anything I'm doing wrong?
- What is the right string I should use for `go get`? Would it be possible to include it in the documentation?

Thanks!

**Comment by joseph-stanton-ax** [comment]
I ran across this issue as well, in the setup.go and setup_test.go the import "github.com/caddyserver/caddy" needs to be changed to "github.com/coredns/caddy". I dropped the plugin directly into the plugin folder of my fork of coredns, so I was able to make the change easily.

**Comment by wenerme** [comment]
@joseph-stanton-ax updated to latest coredns, should works now, if there any problem please reopen.

**Comment by wenerme** [comment]
repo moved to https://github.com/wenerme/coredns-pdsql to support the import requirement
